CREATE OR REPLACE PROCEDURE UPDATE_WELF_DD_2017(
V_SEQ_ID NUMBER,
V_IS_MEMBER_PARTICIPATE NUMBER,
V_IS_SPOUSE_PARTICIPATE NUMBER

)IS



V_MEMBER_EPF  WELF_TRIP_2017_MAIN.EPF_NO%TYPE; 


BEGIN


UPDATE  WELF_TRIP_2017_MAIN SET 
IS_MEMBER_PARTICIPATE=V_IS_MEMBER_PARTICIPATE,
IS_SPOUSE_PARTICIPATE=V_IS_SPOUSE_PARTICIPATE,
SYSTEM_DATE=sysdate
 WHERE SEQ_ID=V_SEQ_ID
;


COMMIT;
EXCEPTION
WHEN OTHERS THEN
raise_application_error(-20001, 'An error was encountered - ' || SQLCODE || ' -ERROR- ' || SQLERRM);
END;
/
