CREATE OR REPLACE PROCEDURE UPDATE_WS_SURVEY_MAIN(
  V_EPF_NO             NUMBER,
  V_BRANCH_CODE        VARCHAR2,
  V_RES_ADDRESS_1      VARCHAR2,
  V_RES_ADDRESS_2      VARCHAR2,
  V_RES_ADDRESS_3      VARCHAR2,
  V_SEX	      		 VARCHAR2,
  V_MARITIAL_STATUS 	 VARCHAR2,
  V_NAME_OF_SPOUSE     VARCHAR2,
  V_NO_OF_CHILDREN  	 NUMBER
)
IS 

BEGIN
      
     
	  
      UPDATE  WS_SURVEY_MAIN SET
		  BRANCH_CODE = V_BRANCH_CODE     ,
		  RES_ADDRESS_1= V_RES_ADDRESS_1    ,
		  RES_ADDRESS_2 =V_RES_ADDRESS_2   ,
		  RES_ADDRESS_3= V_RES_ADDRESS_3    ,
		  SEX=V_SEX	      		,
		  MARITIAL_STATUS=V_MARITIAL_STATUS 	,
		  NAME_OF_SPOUSE =V_NAME_OF_SPOUSE  ,
		  NO_OF_CHILDREN= V_NO_OF_CHILDREN 	,
		  SYSTEM_DATE= SYSDATE       
      WHERE  EPF_NO =  V_EPF_NO   ;
COMMIT;
EXCEPTION
WHEN OTHERS THEN
            raise_application_error(-20001,'An error was encountered - '||SQLCODE||' -ERROR- '||SQLERRM);
END;
/