CREATE OR REPLACE PROCEDURE UPDATE_WELF_TRIP_2017_MAIN(
V_SEQ_ID NUMBER,
V_IS_MEMBER_PARTICIPATE NUMBER,
V_IS_SPOUSE_PARTICIPATE NUMBER,
V_IS_CH1_PARTICIPATE NUMBER,
V_IS_CH2_PARTICIPATE NUMBER,
V_IS_CH3_PARTICIPATE NUMBER,
V_IS_CH4_PARTICIPATE NUMBER,
V_IS_CH5_PARTICIPATE NUMBER,
V_PARTICIPATE_DATE VARCHAR2,
V_MEMBER_COST NUMBER,
V_REMARKS VARCHAR2

)IS

V_ROOM_SEQ_ID WELF_TRIP_2017_ROOM.SEQ_ID%TYPE;
V_SLOT_1_MAIN_SEQ_ID  WELF_TRIP_2017_ROOM.SLOT_1_MAIN_SEQ_ID%TYPE;
V_SLOT_2_MAIN_SEQ_ID WELF_TRIP_2017_ROOM.SLOT_2_MAIN_SEQ_ID %TYPE;
V_SLOT_3_MAIN_SEQ_ID  WELF_TRIP_2017_ROOM.SLOT_3_MAIN_SEQ_ID%TYPE;



V_MEMBER_EPF  WELF_TRIP_2017_MAIN.EPF_NO%TYPE; 
V_MEMBER_GENDER  WELF_TRIP_2017_MAIN.MEMBER_GENDER%TYPE; 


BEGIN
UPDATE  WELF_TRIP_2017_MAIN SET 
IS_MEMBER_PARTICIPATE=V_IS_MEMBER_PARTICIPATE,
IS_SPOUSE_PARTICIPATE=V_IS_SPOUSE_PARTICIPATE,
IS_CH1_PARTICIPATE=V_IS_CH1_PARTICIPATE,
IS_CH2_PARTICIPATE=V_IS_CH2_PARTICIPATE,
IS_CH3_PARTICIPATE=V_IS_CH3_PARTICIPATE,
IS_CH4_PARTICIPATE=V_IS_CH4_PARTICIPATE,
IS_CH5_PARTICIPATE=V_IS_CH5_PARTICIPATE,
PARTICIPATE_DATE=V_PARTICIPATE_DATE,
MEMBER_COST=V_MEMBER_COST,
REMARKS=V_REMARKS,
SYSTEM_DATE=sysdate
 WHERE SEQ_ID=V_SEQ_ID
;

 --SELECT EPF_NO INTO V_MEMBER_EPF FROM WELF_TRIP_2017_MAIN WHERE   SEQ_ID=V_SEQ_ID;
 SELECT MEMBER_GENDER INTO V_MEMBER_GENDER FROM WELF_TRIP_2017_MAIN WHERE   SEQ_ID=V_SEQ_ID;

 
IF (V_IS_SPOUSE_PARTICIPATE=1 OR V_IS_CH1_PARTICIPATE=1 OR V_IS_CH2_PARTICIPATE=1 OR V_IS_CH3_PARTICIPATE=1 OR V_IS_CH4_PARTICIPATE=1 OR V_IS_CH5_PARTICIPATE=1) THEN


		SELECT MIN(SEQ_ID) INTO V_ROOM_SEQ_ID FROM WELF_TRIP_2017_ROOM WHERE AVAILABLE_DATE=V_PARTICIPATE_DATE AND STATUS='AVAILABLE';
 
 
		UPDATE WELF_TRIP_2017_ROOM SET
		  SLOT_1_MAIN_SEQ_ID  =V_SEQ_ID,  
		  STATUS ='FULL'
		 WHERE SEQ_ID=V_ROOM_SEQ_ID;
		 
		  
		UPDATE WELF_TRIP_2017_MAIN SET
		  ROOM_SEQ_ID  =V_ROOM_SEQ_ID
		 WHERE SEQ_ID=V_SEQ_ID;
		 
		 
ELSE

	IF V_IS_MEMBER_PARTICIPATE=1 THEN
	
		SELECT  MIN(SEQ_ID) INTO V_ROOM_SEQ_ID FROM WELF_TRIP_2017_ROOM WHERE AVAILABLE_DATE=V_PARTICIPATE_DATE 
		AND (STATUS='AVAILABLE' OR STATUS='PARTIAL') AND (ROOM_GENDER='NA' OR ROOM_GENDER=V_MEMBER_GENDER);
		
		SELECT  SLOT_1_MAIN_SEQ_ID,SLOT_2_MAIN_SEQ_ID,SLOT_3_MAIN_SEQ_ID  INTO V_SLOT_1_MAIN_SEQ_ID,V_SLOT_2_MAIN_SEQ_ID,V_SLOT_3_MAIN_SEQ_ID FROM WELF_TRIP_2017_ROOM WHERE SEQ_ID=V_ROOM_SEQ_ID;		
		
		
		IF V_SLOT_1_MAIN_SEQ_ID is NULL THEN
			UPDATE WELF_TRIP_2017_ROOM SET
				  SLOT_1_MAIN_SEQ_ID  =V_SEQ_ID,  
				  STATUS ='PARTIAL',
				  ROOM_GENDER=V_MEMBER_GENDER
			WHERE SEQ_ID=V_ROOM_SEQ_ID;
			
					  
			UPDATE WELF_TRIP_2017_MAIN SET
			  ROOM_SEQ_ID  =V_ROOM_SEQ_ID
			 WHERE SEQ_ID=V_SEQ_ID;
		 
		 
		ELSE
			IF V_SLOT_2_MAIN_SEQ_ID is NULL THEN
				UPDATE WELF_TRIP_2017_ROOM SET
					  SLOT_2_MAIN_SEQ_ID  =V_SEQ_ID ,
					  STATUS ='PARTIAL'
				WHERE SEQ_ID=V_ROOM_SEQ_ID;
				
						  
				UPDATE WELF_TRIP_2017_MAIN SET
				  ROOM_SEQ_ID  =V_ROOM_SEQ_ID
				 WHERE SEQ_ID=V_SEQ_ID;
			ELSE
				IF V_SLOT_3_MAIN_SEQ_ID is NULL THEN
					UPDATE WELF_TRIP_2017_ROOM SET
						  SLOT_3_MAIN_SEQ_ID =V_SEQ_ID,
						  STATUS ='FULL'
					WHERE SEQ_ID=V_ROOM_SEQ_ID;
					
							  
					UPDATE WELF_TRIP_2017_MAIN SET
					  ROOM_SEQ_ID  =V_ROOM_SEQ_ID
					 WHERE SEQ_ID=V_SEQ_ID;
				END IF;	
			END IF;		
		END IF;		


			 
	END IF;				
END IF;

COMMIT;
EXCEPTION
WHEN OTHERS THEN
raise_application_error(-20001, 'An error was encountered - ' || SQLCODE || ' -ERROR- ' || SQLERRM);
END;
/
